from modules.func import *
from modules.Game import *


QandA = {
    "Kap1":  {"Text": "You look around the room and see an exit. What do you do?", 
              "Q1": "[1]Go through the exit", 
              "Q2": "[2]Inspect the mysterious table in the middle of the room", 
              "Q3": "[3]Check your status", 
              "Q4": "[4]You are going to sleep because you're some lazy MF"},
              
    "Kap2": {"Text": "You see an old hag outside the cave and she wants to talk to you", 
             "Q1": "[1]Talk with her", 
              "Q2": "[2]Steal her food", 
              "Q3": "[3]Ask for a map of Hyrule",
              "Q4": "[4]You kill her to obtain all her belongings",
              "Q5": "[5]Check your status"},

    "Kap3": {"Text": "You now go into the forest and see a couple of goblins molesting a woman. What do you do?",
             "Q1": "[1]Help her and try to kill the goblins",
             "Q2": "[2]Try distracting the goblins with setting their base camp on fire.",
             "Q3": "[3]Ignoring it and try to loot the goblins' base",
             "Q4": "[4]Check your status",
             "Q5": "[5]Check the map"},

    "Kap4": {"Text": "You now understand the uncomfortable position the woman is in and need to make a decision.",
             "Q1": "[1]Try to rescue her village and defeat one of the 4 great titans Vah Ruta",
             "Q2": "[2]Requesting some items or coins as an equal exchange for saving her village",
             "Q3": "[3]Don't help her and go off into the wild to find other adventures waiting for you",
             "Q4": "[4]Check your status",
             "Q5": "[5]Check the map"},

    "Kap5": {"Text": "You defeated the Titan Vah Ruta and now realized the consequences of Ganon and his evil doing. The village leader also told you about the fire Titan Vah Rudania. ",
             "Q1": "[1]Going to help the people that suffer like the Zora villagers from the Fire Titan Vah Rudania",
             "Q2": "[2]Go on your own adventure to obtain materials and sell them to buy food/equipment with the coins you obtained",
             "Q3": "[3]Check your status",
             "Q4": "[4]Check the map"},

    "Kap6": {"Text": "You defeated the Titan Vah Rudania and learned about the Thunder Titan Vah Naboris from the Gerudo people. They are unable to defeat it due to a curse, but they offer to help you if you can break the curse. What do you do?",
             "Q1": "[1]Accept the Gerudo's help and work together to break the curse and defeat Vah Naboris",
             "Q2": "[2]Refuse the Gerudo's help and try to defeat Vah Naboris on your own",
             "Q3": "[3]Check your status",
             "Q4": "[4]Check the map"},

    "Kap7": {"Text": "You have defeated Vah Rudania and saved the people of the Eldin region. However, there are still two more Titans to defeat before you can face Ganon. What do you do?",
             "Q1": "[1]Head to the next Titan",
             "Q2": "[2]Take a break and explore the area",
             "Q3": "[3]Check your status",
             "Q4": "[4]Check the map"},

    "Kap8": {"Text": "You arrive at the Gerudo Desert, where the second Titan, Vah Naboris, is located. The Gerudo people, however, are hostile towards men. What do you do?",
             "Q1": "[1]Try to find a way to sneak into Gerudo Town",
             "Q2": "[2]Ask for help from the Gorons or Zoras",
             "Q3": "[3]Fight your way through the Gerudo guards",
             "Q4": "[4]Check your status",
             "Q5": "[5]Check the map"},

    "Kap9": {"Text": "You have successfully infiltrated Gerudo Town and made your way to Vah Naboris. However, the Titan is heavily guarded by Yiga Clan assassins. What do you do?",
             "Q1": "[1]Fight your way through the Yiga Clan assassins",
             "Q2": "[2]Sneak past the assassins",
             "Q3": "[3]Ask for help from the Gerudo guards",
             "Q4": "[4]Check your status",
             "Q5": "[5]Check the map"},

    "Kap10": {"Text": "You have defeated Vah Naboris and saved the Gerudo people. There is only one more Titan left to defeat before you can face Ganon. What do you do?",
              "Q1": "[1]Head to the next Titan",
              "Q2": "[2]Take a break and explore the area",
              "Q3": "[3]Check your status",
              "Q4": "[4]Check the map"},

    "Kap11": {"Text": "You arrive at the Rito Village, where the third Titan, Vah Medoh, is located. The Rito people are in danger due to the Titan being controlled by Ganon's forces. What do you do?",
              "Q1": "[1]Help the Rito people by defeating Vah Medoh",
              "Q2": "[2]Ignore the Rito people and continue your own journey",
              "Q3": "[3]Check your status",
              "Q4": "[4]Check the map"},

    "Kap12": {"Text": "You have defeated Vah Medoh and saved the Rito people. All four Titans have been defeated, and now it is time to face Ganon. What do you do?",
              "Q1": "[1]Head to Hyrule Castle and face Ganon",
              "Q2": "[2]Take a break and explore the area",
              "Q3": "[3]Check your status",
              "Q4": "[4]Check the map"},

    "Kap13": {"Text": "As you journey through the desert, you come across a group of travelers who are being attacked by a sandstorm. What do you do?",
              "Q1": "[1]Help the travelers and guide them to safety",
              "Q2": "[2]Ignore the travelers and continue your journey",
              "Q3": "[3]Check your status",
              "Q4": "[4]Check the map"},

    "Kap14": {"Text": "You reach the ancient ruins and find that the artifact is heavily guarded by guardians. What do you do?",
              "Q1": "[1]Fight the guardians and retrieve the artifact",
              "Q2": "[2]Try to sneak past the guardians to get the artifact",
              "Q3": "[3]Find another way to get the artifact",
              "Q4": "[4]Check your status",
              "Q5": "[5]Check the map"},

    "Kap15": {"Text": "With the artifact in your possession, you hear rumors of a secret location hidden deep within the mountains. What do you do?",
              "Q1": "[1]Head to the mountains to investigate the rumors",
              "Q2": "[2]Take a break and explore other parts of the map",
              "Q3": "[3]Check your status",
              "Q4": "[4]Check the map"},

    "Kap16": {"Text": "As you journey through the mountains, you come across a group of villagers who are being attacked by a pack of wolves. What do you do?",
              "Q1": "[1]Help the villagers and fend off the wolves",
              "Q2": "[2]Ignore the villagers and continue your journey",
              "Q3": "[3]Check your status",
              "Q4": "[4]Check the map"},

    "Kap17": {"Text": "You reach the secret location and find that it is guarded by powerful enemies. What do you do?",
              "Q1": "[1]Fight the enemies and explore the location",
              "Q2": "[2]Try to sneak past the enemies to explore the location",
              "Q3": "[3]Find another way to explore the location",
              "Q4": "[4]Check your status",
              "Q5": "[5]Check the map"},

    "Kap18": {"Text": "With the secrets of the location in your possession, you hear rumors of a powerful weapon that can defeat Ganon. What do you do?",
              "Q1": "[1]Search for the weapon to prepare for your final battle with Ganon",
              "Q2": "[2]Take a break and explore other parts of the map",
              "Q3": "[3]Check your status",
              "Q4": "[4]Check the map"},

    "Kap19": {"Text": "With all four Titans defeated, you head towards Hyrule Castle to confront Calamity Ganon. As you approach, you notice a barrier around the castle. What do you do?",
              "Q1": "[1]Attempt to break the barrier with your weapons",
              "Q2": "[2]Look for another way into the castle",
              "Q3": "[3]Return to an earlier save and try a different approach",
              "Q4": "[4]Check your status",
              "Q5": "[5]Check the map"},

    "Kap20": {"Text": "After finding and defeating Ganon's four Blights, the barrier around Hyrule Castle is finally down. You make your way inside the castle and confront Calamity Ganon. What do you do?",
              "Q1": "[1]Use your sword to defeat him head-on",
              "Q2": "[2]Try to weaken him with your bow before engaging in close combat",
              "Q3": "[3]Look for an opportunity to use a special ability to defeat him",
              "Q4": "[4]Check your status",
              "Q5": "[5]Check the map"},

    "Kap21": {"Text": "You've successfully defeated Calamity Ganon and saved the kingdom of Hyrule. Congratulations!",
              "Q1": "[1]Continue playing and exploring the world",
              "Q2": "[2]Start a new game",
              "Q3": "[3]Check your status",
              "Q4": "[4]Check the map"}
}



ChoiceA = {
    "Kap1": {"Q1A": "You follow the light and go through the exit.",
             "Q2A": "You research the mysterious magic table and touch it. A holograph of Zelda appears and explains that you've slept for 100 years and that Hyrule needs your help.",
             "Q3A": "You check your status and see that you have nothing in your inventory, and that you have 10 health points."},
    "Kap2": {"Q1A": "You talk with the old hag, and she tells you that she is the last of her kind and that she is looking for a way to get back to her home. She also tells you that she has a map of Hyrule and wants to give it to you. She gives you some starter equipment and food for your long adventure.",
             "Q2A": "You steal the old hag's food, and she gets angry and attacks you. You fail to defend yourself and are defeated.",
             "Q3A": "The old hag gives you a map of Hyrule and explains that the world is in chaos.", 
             "Q4A": "You try to attack the old hag but she overwhelms you, and you are defeated."},
    "Kap3": {"Q1A": "You helped the woman and killed the goblins. She thanks you and tells you that she is a woman from the Zora Village. She also tells you that her village is in danger because of a flood, which is caused by the Titan Vah Ruta, and tries to persuade you into helping her.",
             "Q2A": "You craft a Molotov cocktail but are too incompetent to throw it and accidentally harm yourself.",
             "Q3A": "You try to loot the goblin's base but they overpower you, and you are defeated."},
    "Kap4": {"Q1A": "You go to the woman's village and fight the Titan Vah Ruhta.",
             "Q2A": "She gives you her sword, which is a holy sword from her village. Then you go to her village and try to defeat the Titan.",
             "Q3A": "You ignore her and venture off to find other adventures waiting for you."},
    "Kap5": {"Q1A": "You travel to the Goronen Village and convince the village leader to help you try defeating the Fire Titan Vah Rudania.",
             "Q2A": "You go and hunt down a rare monster that can only be found near the Zora Village. After you defeated the Monster you head to a Trading outpost to sell coins and buy better Equipment at a nearby Blacksmith",
             "Q2Ab": "After you defeated the Monster you head to a Trading outpost to sell coins and buy better Equipment at a nearby Blacksmith"},
    "Kap6": {"Text": "You defeated the Titan Vah Rudania and learned about the Thunder Titan Vah Naboris from the Gerudo people. They are unable to defeat it due to a curse, but they offer to help you if you can break the curse. What do you do?",
             "Q1": "[1]Accept the Gerudo's help and work together to break the curse and defeat Vah Naboris",
             "Q2": "[2]Refuse the Gerudo's help and try to defeat Vah Naboris on your own",
             "Q3": "[3]Check your status",
             "Q4": "[4]Check the map"},
} 